[bun]
keywords = ["bun", "bun.sh"]
content = """
Bun is a modern JavaScript runtime like Node or Deno. It was built from scratch to focus on three main things:
• Start fast (it has the edge in mind).
• New levels of performance (extending JavaScriptCore, the engine).
• Being a great and complete tool (bundler, transpiler, package manager).

Read more [here](<https://bun.sh/>)
"""

[bug]
keywords = ["bug", "report", "bugs"]
content = """
Found a bug in bun?
• If you are unsure, first discuss your bug in <#887787428973281300> or <#995247410794217553>
• [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=1-bug-report.yml>) and fill out the given template
"""

[feature-request]
keywords = ["feature-request", "feature", "request"]
content = """
Any idea what to add to bun?
• Please consider if this is a request for bun, not for other 3rd party packages
• [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=2-feature-request.yml>) and fill out the given template
"""

[hono]
keywords = ["hono", "express", "server", "routes"]
content = """
**Hono - [炎] means flame🔥 in Japanese**
• Is a small, simple, and ultrafast web framework for Cloudflare Workers, Deno, Bun, and others

[Bun doesn't currently support express because some native modules are missing, but you can use hono for now.](<https://github.com/honojs/hono#bun>)
"""

[not-same-file-system]
keywords = ["not-same-file-system", "backend copyfile", "copyfile"]
content = """
**error: NotSameFileSystem installing [package]**

Bun uses hardlinks for installation by default.
Due to technical limitations, hardlinks won't work with different partitions, to evade this limitation, use the `--backend=copyfile` flag.
"""

[windows]
keywords = ["windows", "windows support"]
content = """
Bun does not currently have support for Windows, so you must use WSL (Windows Subsystem for Linux).
To install WSL, check [microsoft documentation](<https://docs.microsoft.com/en-us/windows/wsl/install>)
"""

[io-uring-not-supported]
keywords = ["io-uring-is-not-supported", "io uring", "not supported", "support"]
content = """
To fix `Linux kernel version doesn't support io_uring, which Bun depends on` error, you need to update Linux kernel.

If you are using the Windows Subsystem for Linux, do:
1. Open powershell
2. Run:
    • wsl --set-version <distro name> 2
    • wsl --shutdown
"""