[bun]
keywords = ["bun", "bun.sh"]
content = """
Bun is an all-in-one JavaScript runtime & toolkit designed for speed, complete with a bundler, test runner, and Node.js-compatible package manager.

Read more [here](<https://bun.sh/>)
"""

[bug]
keywords = ["bug", "report", "bugs"]
content = """
Found a bug in bun?
- If you are unsure, first discuss your bug in <#887787428973281300> or <#995247410794217553>
- [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=1-bug-report.yml>) and fill out the given template
"""

[feature-request]
keywords = ["feature-request", "feature", "request"]
content = """
Any idea what to add to bun?
- Please consider if this is a request for bun, not for other 3rd party packages
- [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=2-feature-request.yml>) and fill out the given template
"""

[tags]
keywords = ["contributing-tags", "contributing", "tags"]
content = """
To create or update tag, check [xHyroM/bun-discord-bot#contributing-tags](<https://github.com/xHyroM/bun-discord-bot/#contributing-tags>)
"""

[windows]
keywords = ["windows", "windows support"]
content = """
Bun does not currently have support for Windows, so you must use WSL (Windows Subsystem for Linux).
To install WSL, check [microsoft documentation](<https://docs.microsoft.com/en-us/windows/wsl/install>)
"""

[io-uring-is-not-supported]
keywords = ["io-uring-is-not-supported", "io uring", "not supported", "support", "linux", "kernel", "update"]
content = """
**error: Linux kernel version doesn't support io_uring, which Bun depends on**

To fix this error, you need to update Linux kernel.
If you are using the Windows Subsystem for Linux, do:
  **1.** Open powershell as administrator
  **2.** Run:
     - wsl --set-version <disto name> 2
       - If it throws `Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.`, turn on Virtual Machine Platform in Windows Features and then rerun this command.
       - PS: You can get distro name from `wsl --list -v` 
     - wsl --update
     - wsl --shutdown

If that doesn't work (and you're on a Windows machine), try this:
  **1.** Open Windows Update
  **2.** Download any updates to Windows Subsystem for Linux
"""

[illegal-instruction]
keywords = ["illegal-instruction", "core-dumped", "dumped", "core", "illegal"]
content = """
**Illegal instruction - core dumped**

Update to latest version using:
+++
curl https://bun.sh/install | bash
+++

or install latest *-baseline build from [GitHub Releases](<https://github.com/oven-sh/bun/releases>)
"""

# common questions

[ts] # 'how do i use typescript or jsx?'
keywords = ["typescript", "tsc"]
content = """
Bun supports TypeScript and JSX out of the box. They can be run directly with [`bun run`](https://bun.sh/docs/cli/run).
For setting up IDE support, [documentation page on TypeScript](https://bun.sh/docs/runtime/typescript)
"""

[nix] # 'it doesnt work on nixos'
keywords = ["nix", "nixos"]
content = """
To use Bun on NixOS, you must install it through the nix package manager using [the `bun` package in nixpkgs](https://search.nixos.org/packages?channel=unstable&show=bun&from=0&size=1&sort=relevance&type=packages&query=bun):

+++
nix-env -iA nixos.bun
+++

Using `bun upgrade` or the curl installer will not work because NixOS does not provide `ld.so` which means any non-nixos linux executables will not work (you'll see "File not found" when trying to run them, even though the binary is there).
"""
