[bun]
keywords = ["bun", "bun.sh"]
content = """
Bun is a modern JavaScript runtime like Node or Deno. It was built from scratch to focus on three main things:
• Start fast (it has the edge in mind).
• New levels of performance (extending JavaScriptCore, the engine).
• Being a great and complete tool (bundler, transpiler, package manager).

Read more [here](<https://bun.sh/>)
"""

[bug]
keywords = ["bug", "report", "bugs"]
content = """
Found a bug in bun?
• If you are unsure, first discuss your bug in <#887787428973281300> or <#995247410794217553>
• [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=1-bug-report.yml>) and fill out the given template
"""

[feature-request]
keywords = ["feature-request", "feature", "request"]
content = """
Any idea what to add to bun?
• Please consider if this is a request for bun, not for other 3rd party packages
• [Open an issue on GitHub](<https://github.com/oven-sh/bun/issues/new?template=2-feature-request.yml>) and fill out the given template
"""

[hono]
keywords = ["hono", "express", "server", "routes"]
content = """
**Hono - [炎] means flame🔥 in Japanese**
• Is a small, simple, and ultrafast web framework for Cloudflare Workers, Deno, Bun, and others

[Bun doesn't currently support express because some native modules are missing, but you can use hono for now.](<https://github.com/honojs/hono#bun>)
"""

[not-same-file-system]
keywords = ["not-same-file-system", "backend copyfile", "copyfile"]
content = """
**error: NotSameFileSystem installing [package]**

You have old bun. Use `bun upgrade` to upgrade.
If you have problems with upgrade, reinstall bun using `curl https://bun.sh/install | bash`
"""

[windows]
keywords = ["windows", "windows support"]
content = """
Bun does not currently have support for Windows, so you must use WSL (Windows Subsystem for Linux).
To install WSL, check [microsoft documentation](<https://docs.microsoft.com/en-us/windows/wsl/install>)
"""

[io-uring-not-supported]
keywords = ["io-uring-is-not-supported", "io uring", "not supported", "support"]
content = """
**error: Linux kernel version doesn't support io_uring, which Bun depends on**

To fix this error, you need to update Linux kernel.
If you are using the Windows Subsystem for Linux, do:
  **1.** Open powershell as administrator
  **2.** Run:
     • wsl --set-version <distro name> 2
     • wsl --shutdown
"""

[illegal-instruction]
keywords = ["illegal-instruction", "core-dumped", "dumped", "core", "illegal"]
cotent = """
**Illegal instruction - core dumped**

Bun currently only works on CPUs supporting the AVX2 instruction set.
To run on older CPUs this can be emulated using Intel SDE, however bun won't be as fast as it would be when running on CPUs with AVX2 support.
If you get this error while bun is initializing, you probably need to wrap the bun executable with intel-sde.

**1.** Install intel-sde:
   • Arch Linux: `yay -S intel-sde`
   • Other Distros:
```bash
wget https://downloadmirror.intel.com/732268/sde-external-9.7.0-2022-05-09-lin.tar.xz -O /tmp/intel-sde.tar.xz
cd /tmp
tar -xf intel-sde.tar.xz
cd sde-external*
mkdir /usr/local/bin -p
cp sde64 /usr/local/bin/sde
cp -r intel64 /usr/local/bin/
cp -r misc /usr/local/bin/
```

**2.** Add alias to bashrc
   • `echo "alias bun='sde -chip-check-disable -- bun'" >> ~/.bashrc`
"""